# This check runs only on the release PR created by changesets.
# It requires that a label is added to ensure that peer dependency versions have been manually reviewed

name: Check peer dependency versions have been reviewed

on:
  merge_group:
  pull_request:
    branches:
      - changeset-release/main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited

jobs:
  check-label:
    name: Check peer dependency versions have been reviewed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Check if PR links to documentation
        if: github.event_name == 'pull_request'
        env:
          GITHUB_EVENT_PULL_REQUEST_LABELS: ${{ toJson(github.event.pull_request.labels) }}
        run: node scripts/validate-peer-dependencies-reviewed-label.mjs
