name: Create release PR / Publish packages

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  pr:
    name: Conditionally create a release PR
    runs-on: ubuntu-latest
    outputs:
      hasChangesets: ${{ steps.store-has-changesets.outputs.hasChangesets }}
    permissions:
      pull-requests: write # This allows us to create pull requests
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          # NOTE: If we use default GITHUB_TOKEN to create the release PR, the checks on the release PR will not be triggered automatically
          token: ${{ secrets.RELEASE_GITHUB_TOKEN || github.token }}

      - name: Set up the environment
        uses: ./.github/actions/setup-env

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Create release Pull Request
        id: pr
        env:
          # NOTE: If we use the default GITHUB_TOKEN to create the release PR, the checks on the release PR will not be triggered automatically
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN || github.token }}
        uses: changesets/action@v1
        with:
          title: Version Packages (v3)
          version: pnpm version-for-release

      - name: Store hasChangesets for subsequent jobs
        id: store-has-changesets
        run: |
          echo "hasChangesets=${{steps.pr.outputs.hasChangesets}}"
          echo "hasChangesets=${{steps.pr.outputs.hasChangesets}}" >> $GITHUB_OUTPUT
